config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index'

  devise_for :users

  resources :users do
    resources :tasks
  end

  resources :tasks do
    resources :comments
  end

  resources :attachments

end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :attachments
  attr_accessor :attachments, :remove_attachments

  # Mount and serialize attachments for multiple file uploads
  mount_uploaders :attachments, AttachmentUploader
  serialize :attachments, JSON # JSON datatype doesn't exists in SQLite

  # Task name Validation
  validates :task, presence: true, length: { minimum: 2 }

end

app/controllers/tasks_controller.rb
# Controller for handling all task manipulation
class TasksController < ApplicationController

  # Find task in method first to prevent duplicate code
  before_action :find_task, only: [:show, :edit, :update, :destroy]

  # Only allow non users to view index and tasks, can not edit or delete
  before_action :authenticate_user!, except: [:index, :show]

  attr_accessor :task

  # GET /tasks
  # If params are set to :terms user is searching for tasks
  # True -> Get tasks that match searched terms
  # False -> Get all tasks
  def index
    @tasks = if params[:term]
    @task = Task.where('task LIKE ?', "%#{params[:term]}%")
    else
      @task = Task.all
    end
  end

  # GET /tasks/TASK ID
  def show

  end

  # GET /tasks/new
  # @task -> Gets new task for current user logged in
  def new
    @task = current_user.tasks.build
  end

  # GET /tasks/TASK ID/edit
  def edit

  end

  # POST /tasks
  # @task -> Creates new task in db from data collected from user
  # Checks if task was saved to db
  # True -> Successful db entry, returns to task and display msg OR shows data in json based on request
  # False -> db entry failed, show form with error msg OR shows data in json based on request
  # Return format based on client request
  def create
    @task = current_user.tasks.build(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created!' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, notice: 'Task was not created, please try again.' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # Action updates existing task based task id
  # Checks if task was updated to db
  # True -> Successful db update, returns to task and display msg OR shows data in json based on request
  # False -> db update failed, show form with error msg OR shows data in json based on request
  # Return format based on client request
  def update

    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, notice: 'Task could not be updated, please try again.' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # Action deletes existing task based task id
  # Will also delete task comments and attachments
  # After deleting task redirect user to tasks index page with msg
  # Return json format based on client request
  def destroy
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_path, notice: 'The task was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  # Private can't be called outside intended context
  private

  # Gets current task from id in params
  def find_task
    @task = Task.find(params[:id])
  end

  # Task params collected from user when creating new task
  def task_params
    params.require(:task).permit(
        :task,
        :details,
        :due_date,
        { attachments: [] },
        :status,
        :remove_attachments,
        :term
    )
  end

end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_attachments.html.erb
<%
  @task_id_num_string = @task.id.to_s
  @domain = 'http://localhost:3000'
  @task_attacment_dir = @domain + "/uploads/task/attachments/" + @task_id_num_string + "/"
  @dir = "#{Rails.root}/public/uploads/task/attachments/" + @task_id_num_string + "/*"
  @files = Dir.glob(@dir)
  @intersection = @files - @task.attachments
%>

<!--
<% @task.attachments.each do |a| %>
    <% link_to icon("trash"),
                attachment_url(a),
                method: :delete,
                data: { confirm: 'Are you sure you would like to delete ' + a.url.split("/").last + '?' }
    %>

    <!--<%= link_to a.url.split("/").last, a.url %>-->
    <br/>
    <!--<% end %><br />-->

<% if !@intersection.empty? %>
    <%= @intersection.size %>
    <strong>Attachments Found:</strong><br/>
<% else %>
    <p><strong>No Attachments Found.</strong></p>
<% end %>

<div class="attachment-name">
<% @intersection.each do |file| %>
    <!--<% file_name = file.split('/').last %>
    <%= link_to icon("trash"),
                @task_attacment_dir + file_name,
                method: :delete,
                data: { confirm: 'Are you sure you would like to delete ' + file_name + '?' }
    %>-->
    <%= link_to file_name, @task_attacment_dir + file_name %><br />
<% end %>
</div>

app/views/tasks/_form.html.erb
<%= form_with model: @task, local: true do |form| %>
    <% if @task.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>
          <ul>
            <% @task.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div><!--/error-->
    <% end %>

    <div class="row">
      <div class="col">
        <div class="form-group">
          <%= form.label :task %><br>
          <%= form.text_field :task, autofocus: true, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :details %><br>
          <%= form.text_area :details, class: 'form-control' %>
        </div>
      </div><!--/row-->

      <div class="col">
        <div class="form-group">
          <%= form.label :attachments %><br/>
          <% @task.attachments.each do |a| %>
              <%= link_to a.url.split("/").last, a.url %><br />
          <% end %>

          <br />
          <%= form.file_field :attachments, multiple: true %>
        </div>

        <div class="form-group">
          <%= form.label :due_date %><br>
          <%= form.text_field :due_date, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :status %><br>
          <%= select(:task, :status, %w[Pending Started On\ Hold Completed Archived], class: 'form-control') %>
        </div>

      </div><!--/col-->
    </div><!--/row-->

    <div class="actions form-group">
      <%= form.submit class: 'btn btn-primary' %>
    </div>

<% end %>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<h1>Listing All Tasks</h1>

<%= form_tag(@tasks_path, method: :get, class: "form-inline") do %>
    <%= text_field_tag :term, params[:term], class: "form-control" %>
    <%= submit_tag 'Search', name: nil, class: "btn btn-primary"%>
<% end %><br/>

<div class="table-responsive">
    <table class="table table-hover table-sm table-bordered">
      <tr>
        <th scope="col">Task</th>
        <th scope="col">Details</th>
        <th scope="col">User</th>
        <th scope="col">Due Date</th>
        <th scope="col">Status</th>
        <th scope="col">View</th>
        <th scope="col">Edit</th>
        <th scope="col">Delete</th>
      </tr>

      <% @task.each do |task| %>
          <tr>
            <td><%= task.task %></td>
            <td><%= task.details %></td>
            <td><%= task.user.email.split("@").first %></td>
            <td><%= task.due_date %></td>
            <td><%= task.status %></td>
            <td style ='text-align: center;'><%= link_to icon('eye', '', class: 'fa-fw'), task_path(task) %></td>
            <% if task.user == current_user %>
              <td style ='text-align: center;'><%= link_to icon('pencil', '', class: 'fa-fw'), edit_task_path(task) %></td>
              <td style ='text-align: center;'><%= link_to icon('trash', '', class: 'fa-fw'), task_path(task),
                            method: :delete,
                            data: { confirm: 'Are you sure?' } %></td>
            <% end %>
          </tr>
      <% end %>

    </table>
</div><!--/table-responsive-->

<ul class="pagination">
  <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
  <li class="page-item active"><a class="page-link" href="#">1</a></li>
  <li class="page-item disabled"><a class="page-link" href="#">2</a></li>
  <li class="page-item disabled"><a class="page-link" href="#">3</a></li>
  <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
</ul>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

app/views/tasks/show.html.erb
<h1>View Task</h1>
<% if @task.user == current_user %>
    <td><%= link_to 'Edit', edit_task_path(@task) %> |</td>
    <td><%= link_to 'Delete', task_path(@task),
                    method: :delete,
                    data: { confirm: 'Are you sure?' } %> |</td>
<% end %>

<%= link_to 'Back', tasks_path %><br/>

<div class="row">
  <div class="col-sm-6">
    <p><strong>Task: </strong><%= @task.task %></p>

    <p><strong>User: </strong><%= @task.user.email.split("@").first %></p>

    <p><strong>Due Date: </strong><%= @task.due_date %></p>

    <p><strong>Status: </strong><%= @task.status %></p>

    <p><strong>Details: </strong><%= @task.details %></p>
  </div><!--/col-sm-6-->

  <div class="col-sm-6">
    <%= render 'tasks/attachments' %>
  </div><!--/col-sm-6-->
</div><!--/row-->

<hr/>
<h1 class="text-center">Comments</h1>
<%= render @task.comments %>

<h3>Add a comment</h3>
<%= render 'comments/form' %>